// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/auth/login" | "/[locale]/auth/register" | "/about" | "/admin" | "/admin/content" | "/admin/content/[licenseId]" | "/admin/content/[licenseId]/topic/[topicId]" | "/admin/content/questions" | "/admin/coupons" | "/admin/modules" | "/admin/plans" | "/admin/users" | "/api/signatories/verify/[token]" | "/app" | "/app/account" | "/app/balloons" | "/app/balloons/bregs" | "/app/balloons/hub" | "/app/balloons/logbook" | "/app/e" | "/app/e/hub" | "/app/e/logbook" | "/app/e/rating-avionics" | "/app/e/standard-practices" | "/app/hub" | "/app/m" | "/app/m/airframe" | "/app/m/hub" | "/app/m/logbook" | "/app/m/powerplant" | "/app/m/standard-practices" | "/app/onboarding" | "/app/regs" | "/app/regs/cars" | "/app/regs/standards" | "/app/s" | "/app/s/hub" | "/app/s/logbook" | "/app/s/rating-structures" | "/app/s/standard-practices" | "/app/student" | "/auth/forgot-password" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/become-ame" | "/dev/signatory-test" | "/feedback" | "/help" | "/instructions" | "/pricing" | "/privacy" | "/question/[id]" | "/sign/[token]" | "/signatory/verify/[token]" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/content" | "/api/admin/content/[questionId]" | "/api/admin/content/import" | "/api/admin/content/metadata" | "/api/admin/coupons" | "/api/admin/coupons/[couponId]" | "/api/admin/license-entitlements" | "/api/admin/licenses" | "/api/admin/licenses/[licenseId]" | "/api/admin/modules" | "/api/admin/modules/[moduleId]" | "/api/admin/plans" | "/api/admin/plans/[planId]" | "/api/admin/subjects" | "/api/admin/subjects/[subjectId]" | "/api/admin/topics" | "/api/admin/topics/[topicId]" | "/api/admin/users" | "/api/admin/users/[userId]" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/verify" | "/api/checkout" | "/api/entitlements/enroll-license" | "/api/entitlements/set-plan" | "/api/logbook/create" | "/api/me/billing-portal" | "/api/me/onboarding" | "/api/me/password" | "/api/me/profile" | "/api/me/student" | "/api/plans" | "/api/question-by-id" | "/api/sign-request/create" | "/api/sign/confirm" | "/api/signatories/list" | "/api/signatories/send-verify" | "/api/signatories/upsert" | "/api/signatories/verify" | "/api/signatory/[id]/send-verify" | "/api/signatory/[id]/update" | "/api/signatory/create" | "/api/signatory/verify" | "/api/study/session/finish" | "/api/study/session/start" | "/api/webhooks/stripe"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/app" | "/app/balloons" | "/app/balloons/bregs" | "/app/balloons/logbook" | "/app/e" | "/app/e/logbook" | "/app/e/rating-avionics" | "/app/e/standard-practices" | "/app/hub" | "/app/m" | "/app/m/airframe" | "/app/m/powerplant" | "/app/m/standard-practices" | "/app/regs" | "/app/s" | "/app/s/logbook"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/auth/login": { "locale": string; }
  "/[locale]/auth/register": { "locale": string; }
  "/about": {}
  "/admin": {}
  "/admin/content": {}
  "/admin/content/[licenseId]": { "licenseId": string; }
  "/admin/content/[licenseId]/topic/[topicId]": { "licenseId": string; "topicId": string; }
  "/admin/content/questions": {}
  "/admin/coupons": {}
  "/admin/modules": {}
  "/admin/plans": {}
  "/admin/users": {}
  "/api/admin/content": {}
  "/api/admin/content/[questionId]": { "questionId": string; }
  "/api/admin/content/import": {}
  "/api/admin/content/metadata": {}
  "/api/admin/coupons": {}
  "/api/admin/coupons/[couponId]": { "couponId": string; }
  "/api/admin/license-entitlements": {}
  "/api/admin/licenses": {}
  "/api/admin/licenses/[licenseId]": { "licenseId": string; }
  "/api/admin/modules": {}
  "/api/admin/modules/[moduleId]": { "moduleId": string; }
  "/api/admin/plans": {}
  "/api/admin/plans/[planId]": { "planId": string; }
  "/api/admin/subjects": {}
  "/api/admin/subjects/[subjectId]": { "subjectId": string; }
  "/api/admin/topics": {}
  "/api/admin/topics/[topicId]": { "topicId": string; }
  "/api/admin/users": {}
  "/api/admin/users/[userId]": { "userId": string; }
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify": {}
  "/api/checkout": {}
  "/api/entitlements/enroll-license": {}
  "/api/entitlements/set-plan": {}
  "/api/logbook/create": {}
  "/api/me/billing-portal": {}
  "/api/me/onboarding": {}
  "/api/me/password": {}
  "/api/me/profile": {}
  "/api/me/student": {}
  "/api/plans": {}
  "/api/question-by-id": {}
  "/api/sign-request/create": {}
  "/api/sign/confirm": {}
  "/api/signatories/list": {}
  "/api/signatories/send-verify": {}
  "/api/signatories/upsert": {}
  "/api/signatories/verify": {}
  "/api/signatories/verify/[token]": { "token": string; }
  "/api/signatory/[id]/send-verify": { "id": string; }
  "/api/signatory/[id]/update": { "id": string; }
  "/api/signatory/create": {}
  "/api/signatory/verify": {}
  "/api/study/session/finish": {}
  "/api/study/session/start": {}
  "/api/webhooks/stripe": {}
  "/app": {}
  "/app/account": {}
  "/app/balloons": {}
  "/app/balloons/bregs": {}
  "/app/balloons/hub": {}
  "/app/balloons/logbook": {}
  "/app/e": {}
  "/app/e/hub": {}
  "/app/e/logbook": {}
  "/app/e/rating-avionics": {}
  "/app/e/standard-practices": {}
  "/app/hub": {}
  "/app/m": {}
  "/app/m/airframe": {}
  "/app/m/hub": {}
  "/app/m/logbook": {}
  "/app/m/powerplant": {}
  "/app/m/standard-practices": {}
  "/app/onboarding": {}
  "/app/regs": {}
  "/app/regs/cars": {}
  "/app/regs/standards": {}
  "/app/s": {}
  "/app/s/hub": {}
  "/app/s/logbook": {}
  "/app/s/rating-structures": {}
  "/app/s/standard-practices": {}
  "/app/student": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/become-ame": {}
  "/dev/signatory-test": {}
  "/feedback": {}
  "/help": {}
  "/instructions": {}
  "/pricing": {}
  "/privacy": {}
  "/question/[id]": { "id": string; }
  "/sign/[token]": { "token": string; }
  "/signatory/verify/[token]": { "token": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/app": never
  "/app/balloons": never
  "/app/balloons/bregs": never
  "/app/balloons/logbook": never
  "/app/e": never
  "/app/e/logbook": never
  "/app/e/rating-avionics": never
  "/app/e/standard-practices": never
  "/app/hub": never
  "/app/m": never
  "/app/m/airframe": never
  "/app/m/powerplant": never
  "/app/m/standard-practices": never
  "/app/regs": never
  "/app/s": never
  "/app/s/logbook": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
