// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/[licenseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/[licenseId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/[licenseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/[licenseId]/topic/[topicId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/[licenseId]/topic/[topicId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/[licenseId]/topic/[topicId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/content/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content/questions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/content/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules">> = Specific
  const handler = {} as typeof import("../../src/app/admin/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans">> = Specific
  const handler = {} as typeof import("../../src/app/admin/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatories/verify/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api/signatories/verify/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatories/verify/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/account">> = Specific
  const handler = {} as typeof import("../../src/app/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/bregs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/balloons/bregs">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/bregs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/balloons/hub">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/logbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/balloons/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/logbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/balloons">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/e/hub">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/logbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/e/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/logbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/e">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/rating-avionics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/e/rating-avionics">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/rating-avionics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/standard-practices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/e/standard-practices">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/standard-practices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/hub">> = Specific
  const handler = {} as typeof import("../../src/app/app/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/airframe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m/airframe">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/airframe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m/hub">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/logbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/logbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/powerplant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m/powerplant">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/powerplant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/standard-practices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m/standard-practices">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/standard-practices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/regs/cars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/regs/cars">> = Specific
  const handler = {} as typeof import("../../src/app/app/regs/cars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/regs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/regs">> = Specific
  const handler = {} as typeof import("../../src/app/app/regs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/regs/standards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/regs/standards">> = Specific
  const handler = {} as typeof import("../../src/app/app/regs/standards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/s/hub">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/logbook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/s/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/logbook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/s">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/rating-structures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/s/rating-structures">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/rating-structures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/standard-practices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/s/standard-practices">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/standard-practices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/student">> = Specific
  const handler = {} as typeof import("../../src/app/app/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/become-ame/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/become-ame">> = Specific
  const handler = {} as typeof import("../../src/app/become-ame/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev/signatory-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/signatory-test">> = Specific
  const handler = {} as typeof import("../../src/app/dev/signatory-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/instructions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructions">> = Specific
  const handler = {} as typeof import("../../src/app/instructions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/question/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/question/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/question/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/sign/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signatory/verify/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signatory/verify/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/signatory/verify/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/[questionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content/[questionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/[questionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content/metadata">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/coupons/[couponId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coupons/[couponId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/coupons/[couponId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/coupons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/coupons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/license-entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/license-entitlements">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/license-entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/licenses/[licenseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/licenses/[licenseId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/licenses/[licenseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/licenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/licenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/licenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/modules/[moduleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/modules/[moduleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/modules/[moduleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/modules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/modules">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/modules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/plans/[planId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/plans/[planId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/plans/[planId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/subjects/[subjectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/subjects/[subjectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/subjects/[subjectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/subjects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/subjects">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/subjects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/topics/[topicId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/topics/[topicId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/topics/[topicId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/topics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/topics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/topics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/entitlements/enroll-license/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entitlements/enroll-license">> = Specific
  const handler = {} as typeof import("../../src/app/api/entitlements/enroll-license/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/entitlements/set-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entitlements/set-plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/entitlements/set-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/logbook/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logbook/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/logbook/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/billing-portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/billing-portal">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/billing-portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/student/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/student">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/student/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/question-by-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/question-by-id">> = Specific
  const handler = {} as typeof import("../../src/app/api/question-by-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sign-request/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sign-request/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/sign-request/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sign/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sign/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/sign/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatories/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatories/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatories/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatories/send-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatories/send-verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatories/send-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatories/upsert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatories/upsert">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatories/upsert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatories/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatories/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatories/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatory/[id]/send-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatory/[id]/send-verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatory/[id]/send-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatory/[id]/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatory/[id]/update">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatory/[id]/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatory/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatory/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatory/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatory/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatory/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatory/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/study/session/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study/session/finish">> = Specific
  const handler = {} as typeof import("../../src/app/api/study/session/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/study/session/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study/session/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/study/session/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/bregs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/balloons/bregs">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/bregs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/balloons">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/balloons/logbook/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/balloons/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/balloons/logbook/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/e">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/logbook/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/e/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/logbook/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/rating-avionics/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/e/rating-avionics">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/rating-avionics/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/e/standard-practices/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/e/standard-practices">> = Specific
  const handler = {} as typeof import("../../src/app/app/e/standard-practices/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/hub/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/hub">> = Specific
  const handler = {} as typeof import("../../src/app/app/hub/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/airframe/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/m/airframe">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/airframe/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/m">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/powerplant/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/m/powerplant">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/powerplant/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/m/standard-practices/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/m/standard-practices">> = Specific
  const handler = {} as typeof import("../../src/app/app/m/standard-practices/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/regs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/regs">> = Specific
  const handler = {} as typeof import("../../src/app/app/regs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/s">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/s/logbook/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/s/logbook">> = Specific
  const handler = {} as typeof import("../../src/app/app/s/logbook/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
