BEGIN;

UPDATE "plans"
SET
  "is_active" = false,
  "updated_at" = CURRENT_TIMESTAMP
WHERE "slug" IN ('basic', 'standard', 'premium')
  AND "deleted_at" IS NULL;

INSERT INTO "plans" (
  "slug",
  "name",
  "description",
  "price",
  "max_licenses",
  "flashcards_limit",
  "flashcards_unit",
  "practice_limit",
  "practice_unit",
  "tests_limit",
  "tests_unit",
  "max_questions_per_session",
  "logbook_access",
  "display_order",
  "is_active",
  "created_at",
  "updated_at"
)
VALUES
  (
    'regs-trainee',
    'REGs - Trainee',
    'Regulatory study access for CARs and Standards with controlled daily usage.',
    11.99,
    0,
    25,
    'day',
    2,
    'day',
    2,
    'week',
    NULL,
    false,
    10,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'regs-exam-ready',
    'REGs - Exam Ready',
    'Unlimited regulatory study access for CARs and Standards without logbook.',
    16.99,
    0,
    -1,
    'day',
    -1,
    'day',
    -1,
    'week',
    NULL,
    false,
    20,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'trainee',
    'Trainee',
    'One certification track with daily study limits and no logbook access.',
    19.99,
    1,
    25,
    'day',
    2,
    'day',
    2,
    'week',
    NULL,
    false,
    30,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'license-track',
    'License Track',
    'One certification track with unlimited flashcards and practice plus weekly test allowance.',
    26.99,
    1,
    -1,
    'day',
    -1,
    'day',
    3,
    'week',
    NULL,
    false,
    40,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'exam-ready',
    'Exam Ready',
    'One certification track with full study access and logbook included.',
    34.99,
    1,
    -1,
    'day',
    -1,
    'day',
    -1,
    'week',
    NULL,
    true,
    50,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'logbook-pro',
    'Logbook - Professional Tool',
    'One certification track with logbook access enabled and study modes disabled.',
    9.99,
    1,
    0,
    'day',
    0,
    'day',
    0,
    'week',
    NULL,
    true,
    60,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("slug") DO UPDATE
SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "price" = EXCLUDED."price",
  "max_licenses" = EXCLUDED."max_licenses",
  "flashcards_limit" = EXCLUDED."flashcards_limit",
  "flashcards_unit" = EXCLUDED."flashcards_unit",
  "practice_limit" = EXCLUDED."practice_limit",
  "practice_unit" = EXCLUDED."practice_unit",
  "tests_limit" = EXCLUDED."tests_limit",
  "tests_unit" = EXCLUDED."tests_unit",
  "max_questions_per_session" = EXCLUDED."max_questions_per_session",
  "logbook_access" = EXCLUDED."logbook_access",
  "display_order" = EXCLUDED."display_order",
  "is_active" = EXCLUDED."is_active",
  "deleted_at" = NULL,
  "updated_at" = CURRENT_TIMESTAMP;

COMMIT;